### ISSUE TITLE
Could not find `tests` in `juniper`

### ISSUE THREAD

**Issue by zuijiaoluo** [graphql-rust/juniper_rocket#1]
When I run example.
use juniper::tests::model::Database;

**Comment by adrianperreault** [comment]
You can find the file here: https://github.com/graphql-rust/juniper/blob/master/juniper/src/tests/model.rs

**Comment by theduke** [comment]
The problem here is that the `tests::*` schema is private by default.

There is a feature that makes it public.

You can enable the feature like this:

```toml
[dependencies]
juniper = { git = "...", features = "expose-test-schema" }
```
